# Generated by Django 3.2.3 on 2021-05-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='Mobile',
            new_name='Mobile_No',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Mobile',
            new_name='Mobile_No',
        ),
    ]
