# Generated by Django 3.2.3 on 2021-05-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_auto_20210520_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorDetails',
            new_name='DoctorDetail',
        ),
        migrations.RenameModel(
            old_name='MedicienDetails',
            new_name='MedicienDetail',
        ),
        migrations.RenameModel(
            old_name='PatientDetails',
            new_name='PatientDetail',
        ),
    ]
